-- ============================================================
-- Project Work L-31
-- STEP 7 - Implementazione Oracle SQL
-- Modello dati canonico V2
-- File: 01_schema.sql
--
-- VALIDAZIONE: statica e logico-referenziale.
-- NON risulta eseguito su un'istanza Oracle in questa fase.
-- ============================================================

-- Le chiavi surrogate utilizzano GENERATED BY DEFAULT AS IDENTITY.
-- START WITH 1000 evita collisioni con il dataset dimostrativo,
-- che nello Step 8 utilizzerà ID espliciti nell'intervallo basso.

-- ORGANIZZAZIONI: anagrafica dell'organizzazione del caso di studio.
-- PK: id_organizzazione. FK: nessuna. Vincoli principali: nome obbligatorio.
CREATE TABLE organizzazioni (
    id_organizzazione   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    nome_organizzazione VARCHAR2(150) NOT NULL,

    CONSTRAINT pk_organizzazioni
        PRIMARY KEY (id_organizzazione)
);

-- FORNITORI: anagrafica dei fornitori esterni.
-- PK: id_fornitore. FK: nessuna. Vincoli principali: nome obbligatorio.
CREATE TABLE fornitori (
    id_fornitore   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    nome_fornitore VARCHAR2(150) NOT NULL,

    CONSTRAINT pk_fornitori
        PRIMARY KEY (id_fornitore)
);

-- ASSET: censimento degli asset dell'organizzazione.
-- PK: id_asset. FK: id_organizzazione. Vincoli: criticita e stato nei domini canonici.
CREATE TABLE asset (
    id_asset          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_organizzazione NUMBER(10) NOT NULL,
    nome_asset        VARCHAR2(150) NOT NULL,
    tipo_asset        VARCHAR2(80) NOT NULL,
    criticita         VARCHAR2(10) NOT NULL,
    stato             VARCHAR2(10) NOT NULL,

    CONSTRAINT pk_asset
        PRIMARY KEY (id_asset),

    CONSTRAINT fk_asset_organizzazione
        FOREIGN KEY (id_organizzazione)
        REFERENCES organizzazioni (id_organizzazione),

    CONSTRAINT ck_asset_criticita
        CHECK (criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),

    CONSTRAINT ck_asset_stato
        CHECK (stato IN ('ATTIVO', 'INATTIVO', 'DISMESSO'))
);

-- SERVIZI: censimento dei servizi erogati.
-- PK: id_servizio. FK: id_organizzazione. Vincolo: criticita nel dominio canonico.
CREATE TABLE servizi (
    id_servizio       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_organizzazione NUMBER(10) NOT NULL,
    nome_servizio     VARCHAR2(150) NOT NULL,
    criticita         VARCHAR2(10) NOT NULL,

    CONSTRAINT pk_servizi
        PRIMARY KEY (id_servizio),

    CONSTRAINT fk_servizi_organizzazione
        FOREIGN KEY (id_organizzazione)
        REFERENCES organizzazioni (id_organizzazione),

    CONSTRAINT ck_servizi_criticita
        CHECK (criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA'))
);

-- RESPONSABILI: persone con responsabilita organizzativa o tecnica.
-- PK: id_responsabile. FK: id_organizzazione. Nome, cognome e ruolo obbligatori.
CREATE TABLE responsabili (
    id_responsabile   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_organizzazione NUMBER(10) NOT NULL,
    nome              VARCHAR2(80) NOT NULL,
    cognome           VARCHAR2(80) NOT NULL,
    ruolo             VARCHAR2(120) NOT NULL,

    CONSTRAINT pk_responsabili
        PRIMARY KEY (id_responsabile),

    CONSTRAINT fk_resp_organizzazione
        FOREIGN KEY (id_organizzazione)
        REFERENCES organizzazioni (id_organizzazione)
);

-- PUNTI_CONTATTO: recapiti associati a un responsabile e a una funzione.
-- PK: id_punto_contatto. FK: id_responsabile.
-- Vincoli: priorita positiva, unicita responsabile/funzione/priorita, almeno un recapito.
CREATE TABLE punti_contatto (
    id_punto_contatto NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_responsabile   NUMBER(10) NOT NULL,
    funzione          VARCHAR2(120) NOT NULL,
    priorita_contatto NUMBER(2) NOT NULL,
    email             VARCHAR2(150),
    telefono          VARCHAR2(30),

    CONSTRAINT pk_punti_contatto
        PRIMARY KEY (id_punto_contatto),

    CONSTRAINT fk_pcont_responsabile
        FOREIGN KEY (id_responsabile)
        REFERENCES responsabili (id_responsabile),

    CONSTRAINT uq_pcont_resp_fun_prio
        UNIQUE (id_responsabile, funzione, priorita_contatto),

    CONSTRAINT ck_pcont_priorita
        CHECK (priorita_contatto > 0),

    CONSTRAINT ck_pcont_recapito
        CHECK (email IS NOT NULL OR telefono IS NOT NULL)
);

-- ASSET_SERVIZI: tabella associativa N:M tra asset e servizi.
-- PK composta/FK: id_asset, id_servizio.
CREATE TABLE asset_servizi (
    id_asset    NUMBER(10) NOT NULL,
    id_servizio NUMBER(10) NOT NULL,

    CONSTRAINT pk_asset_servizi
        PRIMARY KEY (id_asset, id_servizio),

    CONSTRAINT fk_aserv_asset
        FOREIGN KEY (id_asset)
        REFERENCES asset (id_asset),

    CONSTRAINT fk_aserv_servizio
        FOREIGN KEY (id_servizio)
        REFERENCES servizi (id_servizio)
);

-- SERVIZI_FORNITORI: dipendenza di un servizio da un fornitore esterno.
-- PK composta: id_servizio, id_fornitore. Entrambe FK.
-- Vincolo: criticita_dipendenza nel dominio canonico.
CREATE TABLE servizi_fornitori (
    id_servizio          NUMBER(10) NOT NULL,
    id_fornitore         NUMBER(10) NOT NULL,
    tipo_dipendenza      VARCHAR2(100) NOT NULL,
    criticita_dipendenza VARCHAR2(10) NOT NULL,
    descrizione          VARCHAR2(500),

    CONSTRAINT pk_servizi_fornitori
        PRIMARY KEY (id_servizio, id_fornitore),

    CONSTRAINT fk_sforn_servizio
        FOREIGN KEY (id_servizio)
        REFERENCES servizi (id_servizio),

    CONSTRAINT fk_sforn_fornitore
        FOREIGN KEY (id_fornitore)
        REFERENCES fornitori (id_fornitore),

    CONSTRAINT ck_sforn_criticita
        CHECK (criticita_dipendenza IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA'))
);

-- ASSET_RESPONSABILI: tabella associativa N:M tra asset e responsabili.
-- PK composta/FK: id_asset, id_responsabile.
CREATE TABLE asset_responsabili (
    id_asset        NUMBER(10) NOT NULL,
    id_responsabile NUMBER(10) NOT NULL,

    CONSTRAINT pk_asset_responsabili
        PRIMARY KEY (id_asset, id_responsabile),

    CONSTRAINT fk_aresp_asset
        FOREIGN KEY (id_asset)
        REFERENCES asset (id_asset),

    CONSTRAINT fk_aresp_responsabile
        FOREIGN KEY (id_responsabile)
        REFERENCES responsabili (id_responsabile)
);

-- SERVIZI_RESPONSABILI: tabella associativa N:M tra servizi e responsabili.
-- PK composta/FK: id_servizio, id_responsabile.
CREATE TABLE servizi_responsabili (
    id_servizio     NUMBER(10) NOT NULL,
    id_responsabile NUMBER(10) NOT NULL,

    CONSTRAINT pk_servizi_responsabili
        PRIMARY KEY (id_servizio, id_responsabile),

    CONSTRAINT fk_sresp_servizio
        FOREIGN KEY (id_servizio)
        REFERENCES servizi (id_servizio),

    CONSTRAINT fk_sresp_responsabile
        FOREIGN KEY (id_responsabile)
        REFERENCES responsabili (id_responsabile)
);

-- DIPENDENZE: dipendenze tecniche asset->asset.
-- PK: id_dipendenza. FK: id_asset_origine e id_asset_richiesto.
-- Vincoli: niente auto-dipendenze e unicita della coppia origine/richiesto.
CREATE TABLE dipendenze (
    id_dipendenza      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_asset_origine   NUMBER(10) NOT NULL,
    id_asset_richiesto NUMBER(10) NOT NULL,
    tipo_dipendenza    VARCHAR2(100) NOT NULL,
    descrizione        VARCHAR2(500),

    CONSTRAINT pk_dipendenze
        PRIMARY KEY (id_dipendenza),

    CONSTRAINT fk_dip_origine
        FOREIGN KEY (id_asset_origine)
        REFERENCES asset (id_asset),

    CONSTRAINT fk_dip_richiesto
        FOREIGN KEY (id_asset_richiesto)
        REFERENCES asset (id_asset),

    CONSTRAINT uq_dip_orig_req
        UNIQUE (id_asset_origine, id_asset_richiesto),

    CONSTRAINT ck_dip_no_self
        CHECK (id_asset_origine <> id_asset_richiesto)
);

-- STORICO_ASSET: snapshot versionati degli asset.
-- PK: id_storico_asset. FK: id_asset.
-- Vincoli: versione positiva/univoca, date coerenti, domini criticita e stato.
CREATE TABLE storico_asset (
    id_storico_asset     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_asset             NUMBER(10) NOT NULL,
    numero_versione      NUMBER(10) NOT NULL,
    data_inizio_validita DATE NOT NULL,
    data_fine_validita   DATE,
    nome_asset           VARCHAR2(150) NOT NULL,
    tipo_asset           VARCHAR2(80) NOT NULL,
    criticita            VARCHAR2(10) NOT NULL,
    stato                VARCHAR2(10) NOT NULL,
    tipo_modifica        VARCHAR2(50) NOT NULL,
    descrizione_modifica VARCHAR2(500),

    CONSTRAINT pk_storico_asset
        PRIMARY KEY (id_storico_asset),

    CONSTRAINT fk_stasset_asset
        FOREIGN KEY (id_asset)
        REFERENCES asset (id_asset),

    CONSTRAINT uq_stasset_ver
        UNIQUE (id_asset, numero_versione),

    CONSTRAINT ck_stasset_ver
        CHECK (numero_versione > 0),

    CONSTRAINT ck_stasset_date
        CHECK (
            data_fine_validita IS NULL
            OR data_fine_validita >= data_inizio_validita
        ),

    CONSTRAINT ck_stasset_crit
        CHECK (criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA')),

    CONSTRAINT ck_stasset_stato
        CHECK (stato IN ('ATTIVO', 'INATTIVO', 'DISMESSO'))
);

-- STORICO_SERVIZI: snapshot versionati dei servizi.
-- PK: id_storico_servizio. FK: id_servizio.
-- Vincoli: versione positiva/univoca, date coerenti, dominio criticita.
CREATE TABLE storico_servizi (
    id_storico_servizio   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
    id_servizio           NUMBER(10) NOT NULL,
    numero_versione       NUMBER(10) NOT NULL,
    data_inizio_validita  DATE NOT NULL,
    data_fine_validita    DATE,
    nome_servizio         VARCHAR2(150) NOT NULL,
    criticita             VARCHAR2(10) NOT NULL,
    tipo_modifica         VARCHAR2(50) NOT NULL,
    descrizione_modifica  VARCHAR2(500),

    CONSTRAINT pk_storico_servizi
        PRIMARY KEY (id_storico_servizio),

    CONSTRAINT fk_stserv_servizio
        FOREIGN KEY (id_servizio)
        REFERENCES servizi (id_servizio),

    CONSTRAINT uq_stserv_ver
        UNIQUE (id_servizio, numero_versione),

    CONSTRAINT ck_stserv_ver
        CHECK (numero_versione > 0),

    CONSTRAINT ck_stserv_date
        CHECK (
            data_fine_validita IS NULL
            OR data_fine_validita >= data_inizio_validita
        ),

    CONSTRAINT ck_stserv_crit
        CHECK (criticita IN ('BASSA', 'MEDIA', 'ALTA', 'CRITICA'))
);
